"""Add age field to students table

Revision ID: 421e0d46c1a3
Revises: 
Create Date: 2025-06-11 20:43:04.613348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '421e0d46c1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('grade')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.String(length=20), nullable=False))
        batch_op.alter_column('credits',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.drop_index(batch_op.f('course_code'))
        batch_op.create_unique_constraint(None, ['course_id'])
        batch_op.drop_column('teacher')
        batch_op.drop_column('course_code')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('score')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.alter_column('class_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=True))
        batch_op.alter_column('class_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('age')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('enrollment_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('grade')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('teacher', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('course_code'), ['course_code'], unique=True)
        batch_op.alter_column('credits',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('course_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
