"""Add enrollment_date to Enrollment model

Revision ID: 95cf582ac1ad
Revises: 3e681210de41
Create Date: 2025-06-17 19:58:11.155443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cf582ac1ad'
down_revision = '3e681210de41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('enrollment_date')

    # ### end Alembic commands ###
